indexSuccess:
    stylesheets:    [button.css]
    javascripts:    []

newSuccess:
    stylesheets:    [form.css, button.css] #Â tooltip.css, validator.css]
    javascripts:    [newPlatform.js, lib/jquery.observe_field.js]

editSuccess:
    stylesheets:    [form.css, input.css, button.css, tooltip.css]
    javascripts:    [editPlatform.js]
